<?php

namespace AppBundle\Repository;

/**
 * HopitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HopitalRepository extends \Doctrine\ORM\EntityRepository
{
}
