<?php

namespace AppBundle\Repository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedecinRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($mot)
    {
        $tr=$this->createQueryBuilder('a');
        $tr->select('a')
            ->where('a.nom LIKE :motcle OR a.postnom LIKE :motcle OR a.id LIKE :motcle')
            ->setParameter('motcle','%'.$mot.'%')
            ->orderBy('a.nom', 'ASC')
            ;
        return $tr->getQuery()->getResult();
    }

    public function recherchePar($value) {
        $tr=$this->createQueryBuilder('a');
        $tr->select('a')
            ->where("a.nom LIKE :motcle OR a.postnom LIKE :motcle")
            ->setParameter('motcle','%'.$value.'%')
            ->orderBy('a.nom', 'ASC');
        return $tr->getQuery()->getResult();
    }

    public function rechercheAvecQualification($value) {
        $tr=$this->createQueryBuilder('a');
        $tr->select('a')
            ->join('a.qualifications', 'q')
            ->join('q.universite', 'u')
            ->join('q.specialite', 's')
            ->where("a.nom LIKE :motcle OR a.postnom LIKE :motcle OR u.id LIKE :motcle OR s.id LIKE :motcle")
            ->setParameter('motcle','%'.$value.'%')
            ->orderBy('a.nom', 'ASC');
        return $tr->getQuery()->getResult();
    }

}
