<?php

namespace AppBundle\Repository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedecinRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($mot)
    {
        $tr=$this->createQueryBuilder('a');
        $tr->select('a')
            ->where('a.nom LIKE :motcle OR a.postnom LIKE :motcle OR a.id LIKE :motcle')
            ->setParameter('motcle','%'.$mot.'%')
            ->orderBy('a.nom', 'ASC')
            ;
        return $tr->getQuery()->getResult();
    }

}
