<?php

namespace AppBundle\Repository;

/**
 * QualificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function rechercheMedecinPar($mot)
    {
        $tr=$this->createQueryBuilder('q');
        $tr->select('q')
            ->join('q.specialite', 's')
            ->join('q.universite', 'u')
            ->join('q.medecin', 'm')->addSelect('m')
            ->where('s.id LIKE :motcle OR u.id LIKE :motcle OR m.id LIKE :motcle OR m.nom LIKE :motcle OR m.postnom LIKE :motcle OR m.prenom LIKE :motcle')
            ->setParameter('motcle','%'.$mot.'%')
            ->orderBy('m.nom', 'ASC')
        ;
        return $tr->getQuery()->getResult();
    }
}
