hopital_index:
    path:     /
    defaults: { _controller: "AppBundle:Hopital:index" }
    methods:  GET

hopital_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Hopital:show" }
    methods:  GET

hopital_new:
    path:     /new
    defaults: { _controller: "AppBundle:Hopital:new" }
    methods:  [GET, POST]

hopital_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Hopital:edit" }
    methods:  [GET, POST]

hopital_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Hopital:delete" }
    methods:  DELETE
