medecin_index:
    path:     /
    defaults: { _controller: "AppBundle:Medecin:index" }
    methods:  GET

liste_medecin:
    path:     /liste-des-medecins
    defaults: { _controller: "AppBundle:Default:liste" }
    methods:  GET
medecin_recherche:
    path:     /medecin-recherche
    defaults: { _controller: "AppBundle:Default:rechercheTraitement" }
    methods:  [GET, POST]
    options:
        expose: true

medecin_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Medecin:show" }
    methods:  GET
medecin_afficher:
    path:     /{id}/afficher
    defaults: { _controller: "AppBundle:Medecin:afficher" }
    methods:  GET
    options:
        expose: true
medecin_new:
    path:     /new
    defaults: { _controller: "AppBundle:Medecin:new" }
    methods:  [GET, POST]

medecin_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Medecin:edit" }
    methods:  [GET, POST]

medecin_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Medecin:delete" }
    methods:  DELETE
